---

# On the volumes section, set the path to you test and training
# paths.
notebook:
  image: "jupyter/all-spark-notebook"
  volumes:
    - "./test_1:/test_1"
    - "./train_1:/train_1"
    - "./work:/home/jovyan/work"
  ports:
    - "8888:8888"
